<?php

use Illuminate\Database\Seeder;
use App\Models\Seat;

class SeatTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // VIP I
        $seat = new Seat();$seat->no = "L1";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L2";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L3";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L4";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L5";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L6";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L7";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L8";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L9";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L10";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L11";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L12";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K1";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K2";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K3";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K4";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K5";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K6";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K7";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K8";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K9";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K10";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K11";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K12";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J1";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J2";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J3";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J4";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J5";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J6";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J7";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J8";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J9";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J10";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J11";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J12";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I1";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I2";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I3";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I4";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I5";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I6";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I7";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I8";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I9";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I10";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I11";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I12";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H1";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H2";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H3";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H4";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H5";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H6";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H7";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H8";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H9";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H10";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H11";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H12";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H13";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H14";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H15";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H16";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H17";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G1";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G2";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G3";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G4";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G5";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G6";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G7";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G8";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G9";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G10";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G11";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G12";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G13";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G14";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G15";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G16";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G17";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F1";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F2";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F3";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F4";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F5";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F6";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F7";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F8";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F9";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F10";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F11";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F12";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F13";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F14";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F15";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F16";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E1";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E2";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E3";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E4";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E5";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E6";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E7";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E8";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E9";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E10";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E11";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E12";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E13";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E14";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E15";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D1";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D2";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D3";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D4";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D5";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D6";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D7";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D8";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D9";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D10";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D11";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D12";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D13";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D14";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D15";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C1";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C2";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C3";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C4";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C5";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C6";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C7";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C8";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C9";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C10";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C11";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C12";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C13";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C14";$seat->ticket_class = "VIP I";$seat->status = "active";$seat->save();

        //VIP H
        $seat = new Seat();$seat->no = "L1";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L2";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L3";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L4";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L5";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L6";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L7";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L8";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L9";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L10";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L11";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L12";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L13";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L14";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L15";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L16";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K1";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K2";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K3";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K4";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K5";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K6";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K7";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K8";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K9";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K10";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K11";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K12";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K13";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K14";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K15";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K16";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J1";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J2";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J3";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J4";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J5";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J6";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J7";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J8";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J9";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J10";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J11";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J12";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J13";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J14";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J15";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J16";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I1";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I2";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I3";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I4";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I5";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I6";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I7";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I8";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I9";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I10";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I11";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I12";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I13";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I14";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I15";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H1";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H2";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H3";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H4";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H5";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H6";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H7";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H8";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H9";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H10";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H11";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H12";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H13";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H14";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H15";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G1";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G2";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G3";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G4";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G5";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G6";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G7";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G8";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G9";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G10";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G11";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G12";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G13";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G14";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G15";$seat->ticket_class = "VIP H";$seat->status = "active";$seat->save();

        // VVIP
        $seat = new Seat();$seat->no = "F1";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F2";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F3";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F4";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F5";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F6";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F7";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F8";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F9";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F10";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F11";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F12";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F13";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F14";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F15";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E1";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E2";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E3";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E4";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E5";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E6";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E7";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E8";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E9";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E10";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E11";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E12";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E13";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E14";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E15";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E16";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E17";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E18";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D1";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D2";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D3";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D4";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D5";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D6";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D7";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D8";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D9";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D10";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D11";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D12";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D13";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D14";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D15";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D16";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D17";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D18";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C1";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C2";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C3";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C4";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C5";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C6";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C7";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C8";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C9";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C10";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C11";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C12";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C13";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C14";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C15";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C16";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C17";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C18";$seat->ticket_class = "VVIP";$seat->status = "active";$seat->save();

        //VIP E
        $seat = new Seat();$seat->no = "L1";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L2";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L3";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L4";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L5";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L6";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L7";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L8";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L9";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L10";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L11";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L12";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L13";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L14";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L15";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L16";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L17";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K1";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K2";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K3";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K4";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K5";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K6";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K7";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K8";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K9";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K10";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K11";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K12";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K13";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K14";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K15";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J1";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J2";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J3";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J4";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J5";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J6";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J7";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J8";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J9";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J10";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J11";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J12";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J13";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J14";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J15";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J16";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I1";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I2";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I3";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I4";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I5";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I6";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I7";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I8";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I9";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I10";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I11";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I12";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I13";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I14";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I15";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I16";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H1";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H2";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H3";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H4";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H5";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H6";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H7";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H8";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H9";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H10";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H11";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H12";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H13";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H14";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H15";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H16";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G1";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G2";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G3";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G4";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G5";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G6";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G7";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G8";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G9";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G10";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G11";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G12";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G13";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G14";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G15";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F1";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F2";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F3";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F4";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F5";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F6";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F7";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F8";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F9";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F10";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F11";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F12";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F13";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F14";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F15";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E1";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E2";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E3";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E4";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E5";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E6";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E7";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E8";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E9";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E10";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E11";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E12";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E13";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E14";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D1";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D2";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D3";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D4";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D5";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D6";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D7";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D8";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D9";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D10";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D11";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D12";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D13";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C1";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C2";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C3";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C4";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C5";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C6";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C7";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C8";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C9";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C10";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C11";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C12";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C13";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C14";$seat->ticket_class = "VIP E";$seat->status = "active";$seat->save();

        //VIP D
        $seat = new Seat();$seat->no = "L1";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L2";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L3";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L4";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L5";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L6";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L7";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L8";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L9";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L10";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L11";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L12";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "L13";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K1";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K2";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K3";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K4";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K5";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K6";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K7";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K8";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K9";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K10";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K11";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "K12";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J1";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J2";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J3";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J4";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J5";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J6";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J7";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J8";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J9";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J10";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J11";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "J12";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I1";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I2";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I3";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I4";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I5";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I6";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I7";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I8";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I9";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I10";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I11";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "I12";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H1";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H2";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H3";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H4";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H5";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H6";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H7";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H8";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H9";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H10";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H11";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H12";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H13";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H14";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H15";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "H16";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G1";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G2";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G3";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G4";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G5";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G6";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G7";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G8";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G9";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G10";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G11";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G12";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G13";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G14";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G15";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "G16";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F1";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F2";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F3";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F4";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F5";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F6";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F7";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F8";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F9";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F10";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F11";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F12";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F13";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F14";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "F15";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E1";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E2";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E3";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E4";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E5";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E6";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E7";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E8";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E9";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E10";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E11";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E12";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E13";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "E14";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D1";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D2";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D3";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D4";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D5";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D6";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D7";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D8";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D9";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D10";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D11";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D12";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D13";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "D14";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C1";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C2";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C3";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C4";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C5";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C6";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C7";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C8";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C9";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C10";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C11";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C12";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C13";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
        $seat = new Seat();$seat->no = "C14";$seat->ticket_class = "VIP D";$seat->status = "active";$seat->save();
    }
}
